package database_test

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"

	"lexiforge/backend/internal/ai"
	"lexiforge/backend/internal/article"
	"lexiforge/backend/internal/config"
	"lexiforge/backend/internal/database"
	"lexiforge/backend/internal/learning"
	"lexiforge/backend/internal/user"
	"lexiforge/backend/internal/vocabulary"
)

type fakeArticleAI struct{}

func (fakeArticleAI) GenerateArticle(_ context.Context, req ai.GenerateArticleRequest) (*ai.GenerateArticleResponse, error) {
	parts := make([]string, 0, len(req.TargetWords))
	claims := make([]ai.CoveredWord, 0, len(req.TargetWords))
	for i, target := range req.TargetWords {
		parts = append(parts, target.Word)
		after := ""
		if i < len(req.TargetWords)-1 {
			after = " "
		}
		claims = append(claims, ai.CoveredWord{
			Spelling:     target.Word,
			Form:         target.Word,
			Occurrence:   1,
			ContextAfter: after,
		})
	}
	return &ai.GenerateArticleResponse{
		Title:           "Integration Article",
		ContentMarkdown: strings.Join(parts, " "),
		Summary:         "Generated by a test fake.",
		CoveredWords:    claims,
		MissingWords:    []string{},
		ModelName:       "fake-integration-model",
		InputTokens:     11,
		OutputTokens:    22,
	}, nil
}

func TestRunMigrationsSeedsLocalUser(t *testing.T) {
	db := openIntegrationDB(t)

	var count int64
	if err := db.Model(&user.User{}).Where("id = ?", user.LocalUserID).Count(&count).Error; err != nil {
		t.Fatalf("count local user: %v", err)
	}
	if count != 1 {
		t.Fatalf("local user count = %d, want 1", count)
	}
}

func TestArticleGenerationPersistsAndReadsPostgresRows(t *testing.T) {
	db := openIntegrationDB(t)
	seedStudyRecords(t, db, 15)

	svc := article.NewService(article.NewRepository(db), fakeArticleAI{})
	got, err := svc.Generate(context.Background(), article.GenerateRequest{
		Topic:           "campus life",
		Difficulty:      "B1-B2",
		ArticleLength:   "medium",
		TargetWordCount: 15,
	})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if got.Status != "succeeded" || got.CoveredWordCount != 15 || got.CoverageRate != 1 {
		t.Fatalf("Generate result = %#v, want full coverage success", got)
	}

	detail, err := svc.Get(context.Background(), got.ArticleID.String())
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
	if detail.Article.Title != "Integration Article" || len(detail.Words) != 15 {
		t.Fatalf("detail title=%q words=%d, want article with 15 words", detail.Article.Title, len(detail.Words))
	}
	if detail.Article.GenerationAttempts != 1 || detail.Article.InputTokens != 11 || detail.Article.OutputTokens != 22 {
		t.Fatalf("article metrics = attempts %d tokens %d/%d, want 1 and 11/22", detail.Article.GenerationAttempts, detail.Article.InputTokens, detail.Article.OutputTokens)
	}
	var run article.ArticleGenerationRun
	if err := db.Where("article_id = ?", got.ArticleID).First(&run).Error; err != nil {
		t.Fatalf("load generation run: %v", err)
	}
	if run.Status != "succeeded" || run.AttemptCount != 1 || run.InputTokens != 11 || run.OutputTokens != 22 {
		t.Fatalf("generation run = %#v, want persisted successful metrics", run)
	}
	for _, word := range detail.Words {
		if !word.IsCovered || word.CharOffset == nil || word.CharLength == nil {
			t.Fatalf("word %#v was not persisted with coverage offsets", word)
		}
	}

	markdown, err := svc.ExportMarkdown(context.Background(), got.ArticleID.String())
	if err != nil {
		t.Fatalf("ExportMarkdown returned error: %v", err)
	}
	if !strings.Contains(markdown, "# Integration Article") || !strings.Contains(markdown, "- [x] term-00") {
		t.Fatalf("markdown output did not include title and covered target words:\n%s", markdown)
	}

	list, err := svc.List(context.Background(), 1, 20)
	if err != nil {
		t.Fatalf("List returned error: %v", err)
	}
	if list.Total != 1 || len(list.Items) != 1 {
		t.Fatalf("list total=%d items=%d, want one article", list.Total, len(list.Items))
	}

	if _, err := svc.UpdateProgress(context.Background(), got.ArticleID.String(), article.ArticleProgressRequest{
		Status: article.ArticleProgressRead,
	}); err != nil {
		t.Fatalf("UpdateProgress(read) returned error: %v", err)
	}
	var exposureCount int64
	if err := db.Model(&learning.WordLearningEvent{}).
		Where("article_id = ? AND event_type = ?", got.ArticleID, learning.EventExposedInArticle).
		Count(&exposureCount).Error; err != nil {
		t.Fatalf("count exposure events: %v", err)
	}
	if exposureCount != 15 {
		t.Fatalf("exposure events = %d, want 15 covered target words", exposureCount)
	}
	if _, err := svc.UpdateProgress(context.Background(), got.ArticleID.String(), article.ArticleProgressRequest{
		Status: article.ArticleProgressRead,
	}); err != nil {
		t.Fatalf("second UpdateProgress(read) returned error: %v", err)
	}
	if err := db.Model(&learning.WordLearningEvent{}).
		Where("article_id = ? AND event_type = ?", got.ArticleID, learning.EventExposedInArticle).
		Count(&exposureCount).Error; err != nil {
		t.Fatalf("recount exposure events: %v", err)
	}
	if exposureCount != 15 {
		t.Fatalf("exposure events after duplicate read = %d, want 15", exposureCount)
	}

	if err := svc.Delete(context.Background(), got.ArticleID.String()); err != nil {
		t.Fatalf("Delete returned error: %v", err)
	}
	if _, err := svc.Get(context.Background(), got.ArticleID.String()); err == nil {
		t.Fatalf("Get after Delete returned nil error, want not found")
	}
}

func TestRecommendationV2PromotesRecentContextFailure(t *testing.T) {
	db := openIntegrationDB(t)
	records := seedStudyRecords(t, db, 16)
	failed := records[len(records)-1]
	userID, err := uuid.Parse(user.LocalUserID)
	if err != nil {
		t.Fatalf("parse local user id: %v", err)
	}
	if err := db.Create(&learning.WordLearningEvent{
		UserID: userID, WordID: failed.WordID, EventType: learning.EventFailedInContext,
		Source: "integration-test", Metadata: datatypes.JSON([]byte(`{}`)),
	}).Error; err != nil {
		t.Fatalf("create failure event: %v", err)
	}

	targets, err := article.NewRepository(db).SelectTargetWords(context.Background(), userID, nil, 15)
	if err != nil {
		t.Fatalf("SelectTargetWords returned error: %v", err)
	}
	if len(targets) != 15 || targets[0].WordID != failed.WordID {
		t.Fatalf("first target = %#v, want recently failed word %s", targets[0], failed.WordID)
	}
	if targets[0].RecommendationReasons["failed_in_context"] != 35 {
		t.Fatalf("recommendation reasons = %#v, want recent failure boost", targets[0].RecommendationReasons)
	}
}

func openIntegrationDB(t *testing.T) *gorm.DB {
	t.Helper()
	dsn := os.Getenv("LEXIFORGE_TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("set LEXIFORGE_TEST_DATABASE_URL to run Postgres integration tests")
	}

	db, err := database.Open(config.Config{
		AppEnv:      "test",
		DatabaseURL: dsn,
		LogLevel:    "warn",
	})
	if err != nil {
		t.Skipf("Postgres integration database unavailable: %v", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("acquire sql.DB: %v", err)
	}
	sqlDB.SetMaxOpenConns(1)

	schema := "lexiforge_test_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	if err := db.Exec("CREATE SCHEMA " + schema).Error; err != nil {
		t.Fatalf("create test schema: %v", err)
	}
	t.Cleanup(func() {
		_ = db.Exec("SET search_path TO public").Error
		_ = db.Exec("DROP SCHEMA IF EXISTS " + schema + " CASCADE").Error
		_ = sqlDB.Close()
	})

	if err := db.Exec("SET search_path TO " + schema).Error; err != nil {
		t.Fatalf("set search_path: %v", err)
	}
	if err := database.RunMigrations(db); err != nil {
		t.Fatalf("RunMigrations: %v", err)
	}
	return db
}

func seedStudyRecords(t *testing.T, db *gorm.DB, count int) []vocabulary.StudyRecord {
	t.Helper()
	userID, err := uuid.Parse(user.LocalUserID)
	if err != nil {
		t.Fatalf("parse LocalUserID: %v", err)
	}
	now := time.Now().UTC()
	records := make([]vocabulary.StudyRecord, 0, count)
	for i := 0; i < count; i++ {
		word := vocabulary.VocabWord{
			ID:            uuid.New(),
			Provider:      "maimemo",
			ProviderVocID: fmt.Sprintf("voc-%02d", i),
			Spelling:      fmt.Sprintf("term-%02d", i),
		}
		if err := db.Create(&word).Error; err != nil {
			t.Fatalf("create vocab word %d: %v", i, err)
		}
		tags := datatypes.JSON([]byte(`["STICKING"]`))
		reasons := datatypes.JSON([]byte(`{"weak_response_FORGET":100}`))
		record := vocabulary.StudyRecord{
			ID:            uuid.New(),
			UserID:        userID,
			WordID:        word.ID,
			Provider:      word.Provider,
			ProviderVocID: word.ProviderVocID,
			LastResponse:  "FORGET",
			StudyCount:    10 + i,
			Tags:          tags,
			MasteryScore:  20,
			WeakScore:     180 - i,
			ScoreVersion:  vocabulary.ScoreVersionV1,
			ScoreReasons:  reasons,
			LastStudyDate: &now,
			LastScoredAt:  &now,
			SyncedAt:      &now,
		}
		if err := db.Create(&record).Error; err != nil {
			t.Fatalf("create study record %d: %v", i, err)
		}
		records = append(records, record)
	}
	return records
}
